/**
 * Issue Creator Agent — creates GitHub issues for each DeFi service
 * that needs to be implemented.
 *
 * This is a deterministic script, not a Claude agent loop — no LLM needed
 * since the task list is predefined.
 *
 * Usage: npx tsx src/agents/issue-agent.ts [--dry-run]
 */
import "dotenv/config";
import { createIssue, ensureLabelExists, listOpenIssues } from "../github.js";

const DRY_RUN = process.argv.includes("--dry-run");
const STAGGER_MS = 60_000; // 60s between issues to avoid rate limits

const SERVICES = [
  {
    name: "wallet",
    title: "implement wallet service",
    body: `Implement \`src/services/wallet.ts\`:
- Load Solana keypair from SOLANA_PRIVATE_KEY env var (base58 encoded)
- Create ethers.Wallet from BASE_PRIVATE_KEY env var
- Export both @solana/kit v2 TransactionSigner and @solana/web3.js v1 Keypair
- Export ethers Wallet for Base operations
- Export Solana Connection (v1) and Rpc (v2)

This service is the compatibility boundary between Kamino (v2) and Mayan (v1).

Generated by issue-agent`,
  },
  {
    name: "kamino",
    title: "implement kamino service",
    body: `Implement \`src/services/kamino.ts\`:
- deposit(amount): deposit SOL as collateral on Kamino main market
- borrow(amount): borrow USDC against collateral
- repay(amount): repay USDC debt
- withdraw(amount): withdraw SOL collateral

Use @kamino-finance/klend-sdk with @solana/kit v2 types from wallet service.
Market address: 7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF
Amounts in base units (lamports for SOL, 1e6 for USDC) using BN.

Generated by issue-agent`,
  },
  {
    name: "mayan",
    title: "implement mayan service",
    body: `Implement \`src/services/mayan.ts\`:
- bridgeToBase(amount): bridge USDC from Solana to Base via Mayan
- bridgeToSolana(amount): bridge USDC from Base to Solana via Mayan
- waitForBridge(txHash): poll explorer API until bridge completes

Use @mayanfinance/swap-sdk with @solana/web3.js v1 types from wallet service.
Use ethers v6 Wallet for Base→Solana direction.

Generated by issue-agent`,
  },
  {
    name: "pipeline",
    title: "implement pipeline service",
    body: `Implement \`src/services/pipeline.ts\`:
- openPosition(): deposit SOL → borrow USDC → bridge USDC to Base
- closePosition(): bridge USDC to Solana → repay USDC → withdraw SOL

Chain wallet, kamino, and mayan services. Each step must await the previous.
Use fixed amounts from src/config.ts (20 SOL collateral, 5 USDC borrow).

Also implement \`src/index.ts\` CLI entry point:
- \`npx tsx src/index.ts open\` → openPosition()
- \`npx tsx src/index.ts close\` → closePosition()

Generated by issue-agent`,
  },
];

(async () => {
  console.log(`\nCreating ${SERVICES.length} service issues\n`);

  if (!DRY_RUN) {
    await ensureLabelExists("implement-service", "0075ca", "Triggers the implementation agent");
  }

  const existingIssues = await listOpenIssues();
  const existingTitles = new Set(existingIssues.map((i) => i.title.toLowerCase()));

  for (const service of SERVICES) {
    if (existingTitles.has(service.title.toLowerCase())) {
      console.log(`Skipping "${service.title}" — issue already exists`);
      continue;
    }

    if (DRY_RUN) {
      console.log(`DRY RUN — would create issue: "${service.title}"`);
      continue;
    }

    const url = await createIssue(service.title, service.body, ["implement-service"]);
    console.log(`Created issue: ${url}`);

    // Stagger issue creation so orchestrators don't all hit the API at once
    const isLast = service === SERVICES[SERVICES.length - 1];
    if (!isLast) {
      console.log(`Waiting ${STAGGER_MS / 1000}s before next issue...`);
      await new Promise((r) => setTimeout(r, STAGGER_MS));
    }
  }
})();
